---
- name: Install Crowdstrike
  hosts: teste
  remote_user: ansible
  become: true

  tasks:
    - name: Baixar pacote do Falcon Sensor 7
      get_url: 
        url: https://ops-sec-csc-finbo.s3.amazonaws.com/sec/CentOS7/falcon-sensor-6.39.0-13601.el7.x86_64.rpm
        dest: "/tmp/falcon-sensor-6.39.0-13601.el7.x86_64.rpm"
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
    
    - name: Baixar pacote do Falcon Sensor 8
      get_url: 
        url: https://ops-sec-csc-finbo.s3.amazonaws.com/sec/CentOS8/falcon-sensor-6.39.0-13601.el8.x86_64.rpm
        dest: "/tmp/falcon-sensor-6.39.0-13601.el8.x86_64.rpm"
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "8"
    
    - name: Instalar Falcon Sensor 7
      yum: 
        name: "/tmp/falcon-sensor-6.39.0-13601.el7.x86_64.rpm"
        state: present
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
    
    - name: Instalar Falcon Sensor 8
      yum: 
        name: "/tmp/falcon-sensor-6.39.0-13601.el8.x86_64.rpm"
        state: present
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "8"
    
    - name: Executar o comando
      shell: sudo /opt/CrowdStrike/falconctl -s --cid=0C0129543AF54146827761EFBF5DDC23-5C
    
    - name: Iniciar serviço falcon-sensor
      systemd:
        name: falcon-sensor
        state: started
